services:
  backend:
    build:
      context: dpp_api/.
    container_name: backend
    ports:
      - "5001:5000"
    volumes:
      - ./dpp_api:/dpp_api
    networks:
      - app-network

  frontend:
    build:
      context: dpp_app/.
    container_name: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./dpp_app:/dpp_app
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000
      - HOST_IP=${HOST_IP}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge